version: '3'

services:
  db:
    image: dannygoldstein/zuds-db:0.1dev
    ports:
       - 8271:5432

  zuds:
    image: dannygoldstein/zuds:0.1dev
    ports:
       - 8174:8888
    links:
       - db
    volumes:
       - .:/home/zuds/demo



