version: '3'

services:

  msgqueue:
    build: ./msgqueue

  ipac-poll-and-pull-service:
    build: ./imcheck
    depends_on:
        - "msgqueue"

  nersc-queue-monitor-service:
    build: ./queuemon
    depends_on:
        - "msgqueue"

  nersc-job-submission-service:
    build: ./pipeline
    depends_on:
        - "msgqueue"
    volumes:
        - ./pipeline/msgconsumer:/daemon
        - ./pipeline:/pipeline

  db:
    build: ./q3cpsql
    