version: '3'

services:

  msgqueue:
    build: ./msgqueue

  ipac-poll-and-pull-service:
    build: ./imcheck
    depends_on:
        - "msgqueue"
        - "db"
        - "nersc-job-submission-service"
    stdin_open: true
    tty: true
    volumes:
        - ./imcheck:/poll
    command: ['bash', '/poll.py', '/poll/plan']

  nersc-queue-monitor-service:
    build: ./queuemon
    depends_on:
        - "msgqueue"
        - "db"
        - "nersc-job-submission-service"

    stdin_open: true
    tty: true


  nersc-job-submission-service:
    build: ./pipeline
    depends_on:
        - "msgqueue"
        - "db"
    volumes:
        - ./pipeline/msgconsumer:/daemon
        - ./pipeline:/pipeline

  db:
    build: ./q3cpsql
    command: [postgres, -c, 'log_statement=all']
