
hpss:
  whereclause: "FIELD=716 AND FID=1 AND CCDID=1 AND QID=1"
  exclude_masks: n

makevariance:
  batch_size: 1024
  frames:

template:
  nimages: 100
  start_date: 2017-12-20T00:00:00.0Z
  end_date: 2018-05-21T00:00:00.0Z


  
  